name: cytodata-single-cell
channels:
- conda-forge
dependencies:
- conda-forge::python=3.7.3
- conda-forge::jupyter=1.0.0
- conda-forge::ipykernel=5.1.3
- conda-forge::nb_conda_kernels=2.2.2
- conda-forge::numpy=1.17.3
- conda-forge::pandas=0.25.3
- conda-forge::scikit-learn=0.21.3
- conda-forge::black=19.10b0
- conda-forge::seaborn=0.9.0
- pip:
  - git+https://github.com/cytomining/pycytominer@3138f3bb0eb19a4cab5bd93e2faf47fce953d82f