name: cytodata-single-cell
channels:
- conda-forge
dependencies:
- conda-forge::python=3.8.0
- conda-forge::jupyter=1.0.0
- conda-forge::ipykernel=5.1.3
- conda-forge::nb_conda_kernels=2.2.2
- conda-forge::numpy=1.17.3
- conda-forge::pandas=0.25.3
- conda-forge::black=19.10b0
